server:
  port: 8000
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS test
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    defer-datasource:
      initialization: true
      database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true


#------------------------------------------------------------
jwt:
  secret-key: U21hcnRTY29yZV9DbHViTWFuYWdlcl9Qcm9qZWN0X1NlY3JldF9LZXlfU21hcnRTY29yZV9DbHViTWFuYWdlcl9Qcm9qZWN0X1NlY3JldF9LZXk=
  access-ttl: 3600 #?(60)*?(60) = 1??

reg-no:
  key: MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXY=